/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servidor;

/**
 *
 * @author hidan
 */
public class viewServidor extends javax.swing.JFrame {

    AlarmServer server;
    int numBanco = 0;

    /**
     * Creates new form viewServidor
     */
    public viewServidor() {
        initComponents();
        try {
            server = new AlarmServer();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        if (server != null) {
            Status.setText("ONLINE");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoAdicionar = new javax.swing.JButton();
        hora = new javax.swing.JTextField();
        minuto = new javax.swing.JTextField();
        segundo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelBanco = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        descricao = new javax.swing.JLabel();
        descricaoTexto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botaoAdicionar.setText("Adicionar");
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoAdicionar);
        botaoAdicionar.setBounds(270, 60, 90, 23);

        hora.setText("0");
        getContentPane().add(hora);
        hora.setBounds(160, 50, 70, 20);

        minuto.setText("0");
        getContentPane().add(minuto);
        minuto.setBounds(160, 70, 70, 20);

        segundo.setText("0");
        getContentPane().add(segundo);
        segundo.setBounds(160, 90, 70, 20);

        jLabel1.setText("Hora");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 50, 23, 14);

        jLabel2.setText("Minuto");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 70, 32, 14);

        jLabel3.setText("Segundo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 90, 50, 14);

        labelBanco.setText("Numero de Alertas no Servidor: 0");
        getContentPane().add(labelBanco);
        labelBanco.setBounds(140, 140, 260, 14);

        Status.setText("Offline");
        getContentPane().add(Status);
        Status.setBounds(90, 280, 32, 14);

        descricao.setText("Descricao:");
        getContentPane().add(descricao);
        descricao.setBounds(90, 10, 70, 14);

        descricaoTexto.setText("jTextField1");
        getContentPane().add(descricaoTexto);
        descricaoTexto.setBounds(160, 10, 210, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed
      
        long tempo = Integer.parseInt(segundo.getText())
                + Integer.parseInt(minuto.getText()) * 60
                + Integer.parseInt(hora.getText()) * 60 * 60;

        if (server.adicionarAlerta(tempo, descricaoTexto.getText()) == true){
            numBanco++;
            labelBanco.setText("Numero de Alertas no Servidor: "+numBanco);
        }
    }//GEN-LAST:event_botaoAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewServidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Status;
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JLabel descricao;
    private javax.swing.JTextField descricaoTexto;
    private javax.swing.JTextField hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelBanco;
    private javax.swing.JTextField minuto;
    private javax.swing.JTextField segundo;
    // End of variables declaration//GEN-END:variables
}
